apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-10-03T08:02:18Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "239"
    uid: ce8142e1-9a9d-483a-ad95-09eaf5586250
  spec:
    clusterIP: 10.96.0.1
    clusterIPs:
    - 10.96.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"react-service","namespace":"default"},"spec":{"ports":[{"nodePort":30091,"port":80,"targetPort":80}],"selector":{"app":"react-site"},"type":"NodePort"}}
    creationTimestamp: "2025-10-03T08:05:19Z"
    name: react-service
    namespace: default
    resourceVersion: "564"
    uid: 52b5ffc0-4c3a-4728-b9dc-f120deec4d98
  spec:
    clusterIP: 10.103.146.104
    clusterIPs:
    - 10.103.146.104
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30091
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: react-site
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx"},"name":"ingress-nginx-controller","namespace":"ingress-nginx"},"spec":{"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"appProtocol":"http","name":"http","port":80,"protocol":"TCP","targetPort":"http"},{"appProtocol":"https","name":"https","port":443,"protocol":"TCP","targetPort":"https"}],"selector":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx"},"type":"NodePort"}}
    creationTimestamp: "2025-10-03T09:28:28Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
    name: ingress-nginx-controller
    namespace: ingress-nginx
    resourceVersion: "5104"
    uid: 96f8af99-523e-402b-b6db-5f44341492ea
  spec:
    clusterIP: 10.108.155.45
    clusterIPs:
    - 10.108.155.45
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - appProtocol: http
      name: http
      nodePort: 31386
      port: 80
      protocol: TCP
      targetPort: http
    - appProtocol: https
      name: https
      nodePort: 31118
      port: 443
      protocol: TCP
      targetPort: https
    selector:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx"},"name":"ingress-nginx-controller-admission","namespace":"ingress-nginx"},"spec":{"ports":[{"appProtocol":"https","name":"https-webhook","port":443,"targetPort":"webhook"}],"selector":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx"},"type":"ClusterIP"}}
    creationTimestamp: "2025-10-03T09:28:28Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
    name: ingress-nginx-controller-admission
    namespace: ingress-nginx
    resourceVersion: "5108"
    uid: 8ec510c3-56ab-4d01-9a4d-ac6b3a92c0a0
  spec:
    clusterIP: 10.107.217.125
    clusterIPs:
    - 10.107.217.125
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - appProtocol: https
      name: https-webhook
      port: 443
      protocol: TCP
      targetPort: webhook
    selector:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "9153"
      prometheus.io/scrape: "true"
    creationTimestamp: "2025-10-03T08:02:20Z"
    labels:
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: CoreDNS
    name: kube-dns
    namespace: kube-system
    resourceVersion: "276"
    uid: 26021764-38ee-4efe-8502-292171d19865
  spec:
    clusterIP: 10.96.0.10
    clusterIPs:
    - 10.96.0.10
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
    selector:
      k8s-app: kube-dns
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"grafana","namespace":"monitoring"},"spec":{"ports":[{"nodePort":31300,"port":3000,"targetPort":3000}],"selector":{"app":"grafana"},"type":"NodePort"}}
    creationTimestamp: "2025-10-03T08:06:52Z"
    name: grafana
    namespace: monitoring
    resourceVersion: "762"
    uid: 15757fcc-3cc5-4bfe-90f4-87f29c4b46bc
  spec:
    clusterIP: 10.97.232.135
    clusterIPs:
    - 10.97.232.135
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31300
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: grafana
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"kube-state-metrics"},"name":"kube-state-metrics","namespace":"monitoring"},"spec":{"ports":[{"name":"http-metrics","port":8080,"targetPort":8080}],"selector":{"app":"kube-state-metrics"},"type":"ClusterIP"}}
    creationTimestamp: "2025-10-03T08:06:52Z"
    labels:
      app: kube-state-metrics
    name: kube-state-metrics
    namespace: monitoring
    resourceVersion: "722"
    uid: 1a81224b-b83b-45af-88a4-02b467d46813
  spec:
    clusterIP: 10.111.44.142
    clusterIPs:
    - 10.111.44.142
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: kube-state-metrics
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"loki","namespace":"monitoring"},"spec":{"ports":[{"port":3100,"targetPort":3100}],"selector":{"app":"loki"},"type":"ClusterIP"}}
    creationTimestamp: "2025-10-04T06:56:14Z"
    name: loki
    namespace: monitoring
    resourceVersion: "12514"
    uid: 38a7a2b0-a44d-4898-84d4-855d1dfc0c54
  spec:
    clusterIP: 10.107.46.152
    clusterIPs:
    - 10.107.46.152
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 3100
      protocol: TCP
      targetPort: 3100
    selector:
      app: loki
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nginx-exporter","namespace":"monitoring"},"spec":{"ports":[{"name":"http","port":9113,"targetPort":"metrics"}],"selector":{"app":"nginx-exporter"}}}
    creationTimestamp: "2025-10-03T08:06:54Z"
    name: nginx-exporter
    namespace: monitoring
    resourceVersion: "805"
    uid: f0724a58-edbc-4f2d-a787-e772fdbcc993
  spec:
    clusterIP: 10.110.185.14
    clusterIPs:
    - 10.110.185.14
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 9113
      protocol: TCP
      targetPort: metrics
    selector:
      app: nginx-exporter
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nginx-service","namespace":"monitoring"},"spec":{"ports":[{"name":"http","nodePort":30081,"port":80,"targetPort":80}],"selector":{"app":"nginx"},"type":"NodePort"}}
    creationTimestamp: "2025-10-03T08:06:54Z"
    name: nginx-service
    namespace: monitoring
    resourceVersion: "791"
    uid: f1fe61bb-f323-47a0-8b54-f0f3d07956ea
  spec:
    clusterIP: 10.102.125.135
    clusterIPs:
    - 10.102.125.135
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30081
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: nginx
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"node-exporter"},"name":"node-exporter","namespace":"monitoring"},"spec":{"ports":[{"name":"metrics","port":9100,"targetPort":9100}],"selector":{"app":"node-exporter"},"type":"ClusterIP"}}
    creationTimestamp: "2025-10-03T08:06:54Z"
    labels:
      app: node-exporter
    name: node-exporter
    namespace: monitoring
    resourceVersion: "824"
    uid: 0240a06f-c428-409b-a60c-c7539fb2d634
  spec:
    clusterIP: 10.101.173.150
    clusterIPs:
    - 10.101.173.150
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
    selector:
      app: node-exporter
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"prometheus","namespace":"monitoring"},"spec":{"ports":[{"nodePort":32390,"port":9090,"targetPort":9090}],"selector":{"app":"prometheus"},"type":"NodePort"}}
    creationTimestamp: "2025-10-03T08:06:53Z"
    name: prometheus
    namespace: monitoring
    resourceVersion: "864"
    uid: e74292ee-7118-434e-bee1-854fe59a4341
  spec:
    clusterIP: 10.111.232.226
    clusterIPs:
    - 10.111.232.226
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 32390
      port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      app: prometheus
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"vault","namespace":"monitoring"},"spec":{"ports":[{"nodePort":30200,"port":8200,"targetPort":8200}],"selector":{"app":"vault"},"type":"NodePort"}}
    creationTimestamp: "2025-10-03T08:06:55Z"
    name: vault
    namespace: monitoring
    resourceVersion: "900"
    uid: 7e2db647-ce48-4a86-8ae4-ef7ed9064f7b
  spec:
    clusterIP: 10.110.245.62
    clusterIPs:
    - 10.110.245.62
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30200
      port: 8200
      protocol: TCP
      targetPort: 8200
    selector:
      app: vault
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"victoria-metrics","namespace":"monitoring"},"spec":{"ports":[{"name":"http","port":8428,"targetPort":8428}],"selector":{"app":"victoria-metrics"}}}
    creationTimestamp: "2025-10-03T08:06:56Z"
    name: victoria-metrics
    namespace: monitoring
    resourceVersion: "918"
    uid: d1bf09ca-f12d-466d-9790-2da5b15e50c4
  spec:
    clusterIP: 10.110.156.33
    clusterIPs:
    - 10.110.156.33
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8428
      protocol: TCP
      targetPort: 8428
    selector:
      app: victoria-metrics
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
