apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-site
  template:
    metadata:
      labels:
        app: react-site
    spec:
      containers:
      - name: react-site
        image: my-react-site:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: NodePort
  selector:
    app: react-site
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30091
